### ISSUE TITLE
WPF for .NET Core 3.0 Planning

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#10649]
Plan MVC (not ASP.NET MVC) content for new Desktop Guide WPF portion.

- [x] Send top tasks to PU #12394
- [x] Iterate on top tasks
- [x] Plan TOC #12395
- [x] ~LT approval~
- [x] Map existing articles to new articles
- [ ] Create articles
  - [x] Overview #13461
  - [ ] Getting started #13776
  - [x] Migration #13463
  - [ ] Fundamentals - XAML/Styles #13471
  - [ ] Fundamentals - Shapes/Accessibility #13472
  - [ ] Working with data #13473
  - [ ] Package and distribute #13474
  - [ ] XAML Services reference scrub #13813

Granted permission to skip MVC for dotnet related content. Woohoo!
