### ISSUE TITLE
[Project]: Create C# 7 content

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1305]
This is a meta-issue that manages [C# 7 content that is part of this project](https://github.com/dotnet/docs/projects/2).

Subtasks are:

- [x] Create the What's New in C# 7 content: #961
- [x] Create the deep dive topic on Tuples: #1113
- [x] Create the deep dive topic on Pattern Matching: #1114
- [x] Update the What's New in C# 7 content for VS 2017 RC: #1277 

Comment below to suggest more topics or improvements in existing topics.
