### ISSUE TITLE
[desktop-guide wpf] Scrub+port the XAML-Services documentation

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#13813]
Related to #10649

XAML services doc set is used a lot throughout the existing documentation. As the existing documentation is ported to the Desktop Guide, the XAML Services docset continues to be referenced.

- The XAML Services probably doesn't need the term ".NET Framework" should be replaced with ".NET" to make it generic.

Steps:

- [x] Move articles from Framework to Desktop-WPF (#16193)
- [x] Scrub articles for .NET Framework to make generic (#16629)
- [x] Fix badly formatted content (indentation and heading spaces) (#17216)
- [x] ~Get articles edited~ Cancelled. Will do later in a different PR.

https://docs.microsoft.com/en-us/dotnet/framework/xaml-services/
