### ISSUE TITLE
[desktop-guide] Todo once merged to master

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#14355]
After the desktop-guide WPF ships:

### File redirects

- [x] From `/dotnet/framework/wpf/controls/styling-and-templating`
  To `docs/desktop-wpf/fundamentals/styles-and-templates-overview.md`
- [x] From `/dotnet/framework/wpf/advanced/xaml-resources`
  To `docs/desktop-wpf/fundamentals/xaml-resources-define.md `
- [x] From `/dotnet/framework/wpf/advanced/xaml-overview-wpf`
  To `docs/desktop-wpf/fundamentals/xaml.md `
- [x] From `/dotnet/framework/wpf/data/data-binding-overview`
  To `docs/desktop-wpf/data/data-binding-overview.md `
- [x] From `docs/core/porting/wpf.md`
  To `dotnet/desktop-wpf/migration/convert-project-from-net-framework`
