### ISSUE TITLE
Updates to install articles (post release)

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#15948]
Related to #14675 (Rewrite the prereqs story for .NET Core)

This issue is to track post-publish work for the new setup area.

- [ ] ~Install specific patch on package managers~ (we've not really received the feedback that this is required. Until we do, I don't think we need to spend time on this)
  
  * On Ubuntu and Debian the format is `{product}-{type}-{version}={patch}-1` (e.g. `dotnet-sdk-3.0=3.0.100-1`)
  * There is no patch command for RHEL
  * On other distros the format is `{product}-{type}-{version}-{patch}-1` (e.g. `dotnet-sdk-3.0-3.0.100-1`)

- [x] Add manual binary install instructions for linux (ARM32 and others do not support the package manager install method. #16014
- [x] Add manual binary install for Windows. #16913
- [x] Add manual binary install for macOS. #17092
- [x] Review existing articles in repo to see if they can be moved here #16062
- [ ] ~Add self-contained requirements to dependencies article~
- [ ] ~Clarify runtime vs Runtime~
- [x] RHEL may not have 3.0 published. #15948
- [x] RHEL may not have ASP.NET Core Runtime published. #15948
- [x] Remove direct install links and point to download pages #16014
- [x] Download link says x32 CPUs instead of x86 CPUs #16014
- [x] ~Install .deb files on debian-based distros #16836~
