### ISSUE TITLE
Plan for "Get Started" (and the next steps in the learning path)

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#17365]
The first task here is to add more potential tutorials. I've added those from issues already created. Suggestions might be:

- [ ] Web site with C# / ASP.NET Razor pages
- [ ] Web API server
- [ ] Mobile client in C# / Xamarin
- [ ] Azure web job to respond to some web event
- [ ] LINQ
- [ ] Using "modern" (or what's new) in C#
- [ ] Object oriented techniques in C#

What else?

**Comment by pkulikov** [comment]
> * Object oriented techniques in C#

That can be complemented with data-oriented techniques in C# (pattern matching already and records in the next versions). However, I guess it would be covered by "Using "modern" C#"?

**Comment by BillWagner** [comment]
***Issues to improve existing content***
- [ ] #17788 - numbers tutorial
- [ ] #12185 Foreach loop in loops, or collections tutorial
- [ ] #1264 - structs in Tour of C#
- [ ] #3276 - Modernize the Tour of C#
- [ ] #9576 - example in tour of C#
- [ ] #13640 - Events description in Tour
- [ ] #17191 - numbers tutorial (again)
- [ ] #8804 local umbers in C#

**Comment by BillWagner** [comment]
***Issues to create new beginner content***
- [ ] #18110 Add Get Started to Jupyter
- [ ] Add LINQ to introduction to C#
- [ ] Incorporate existing Object Oriented content from programming guide. (https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/object-oriented-programming)
- [ ] intro to data and pattern matching
- [ ] Pick a workload: Link to existing starter content for major workload styles.

**Comment by BillWagner** [comment]
***Complete the Journey***
- [ ] Pick a workload: Link to existing starter content for major workload styles
- [ ] organize all get started content to drive toward downloading and using .NET Core as a development platform.

**Comment by BillWagner** [comment]
Closing as the plan is complete.
