### ISSUE TITLE
Epic: New features for C# 9

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#19942]
Track this at the [feature status](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md) page on the roslyn repository. Those features with "Merged" status are already available in preview.

**tasks for each C# 9.0 feature**

- [x] Build plan for each feature
- [x] Create issues for updated reference material
- [x] Create issues for planned tutorials
- [x] Create "Update your skills" section for "what's new" based tutorials.
- [x] Update "what's new in C#" page
- [x] C# 6 - 7.3 content gets moved from "What's new" to appropriate locations as it's not new.

The *Records* and *Pattern matching enhancements* will likely affect the new **Fundamentals** sections. Other features may be covered in advanced, or primarily in **update your skills**

**Comment by BillWagner** [comment]
related: #19705

**Comment by BillWagner** [comment]
List of tasks for [***Records***](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-9.0/records):

- Update language reference for classes & structs to include a section on records. 
- Add a new language reference article for records. This should include information on the compiler generated members, and how to override them. In addition, it should explain inheritance rules for records, primary constructors, with-ers, and deconstruction methods.
- Add a tutorial that uses records and a number of the record features. Readers should learn how to decide between classes, structs, and records.

**Comment by BillWagner** [comment]
List of tasks for [**Top-level statements***](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-9.0/top-level-statements):

- Update the *Tour of C#* "hello world" example to show both formats of the program.
- Provide tutorial for Azure functions using a program with top-level statements. This should include handling command line arguments.
- Update language reference to include the new valid entry points for a C# program. This should include the restrictions on top-level statements and multiple files.

**Comment by BillWagner** [comment]
List of tasks for [***Pattern matching enhancements***](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-9.0/patterns3):

- Update pattern matching tutorial tp include examples using range patterns.
- Consider How-To articles for range patterns (character, number, etc)
- Update Pattern matching language reference with the new pattern syntax.
- Update nullable type articles to include new pattern based null checks. (both nullable value types and nullable reference types)
- Language reference needs updates for the `is` keyword, the `switch` expression page.

**Comment by BillWagner** [comment]
List of tasks for [***Init only setters***](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init):

- Add new "upgrade your skills" tutorial to show how init only setters support immutability.
- Update articles on immutable types to include discussion of init only setters.
- Add `init` keywords to property accessors in language reference.

**Comment by BillWagner** [comment]
***Other features***: My current opinion is the other new features are both targeted in scope and impact for most developers that the following should happen:

- update pertinent language reference section.
- Mention in "what's new" article with a small scoped sample.
- Consider an exploration of all these features (linking to larger tutorials)

**Comment by BillWagner** [comment]
These have all been finished now.
