### ISSUE TITLE
Clean up migration area of .NET guidance

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs#22858]
The migration/porting information has a lot of irrelevant information, such as migrating from [DNX (RC1 of 1.0) to .NET CLI (RC2 of 1.0)](https://docs.microsoft.com/en-us/dotnet/core/migration/from-dnx). All of this old information should be deleted and/or brought up-to-date.

This issue is here to track that effort.

**Migration guide**
- Migration
  - [x] [.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/dotnet/core/migration/20-21) (**DELETE** but move `<DotNetCliToolReference>` info to the [Breaking Changes 2.1 article](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.1)) (#22917)
  - [x] [Migrate from project.json](https://docs.microsoft.com/en-us/dotnet/core/migration/index) (**DELETE** project.json/.xproj/DNX material hasn't applied for years.) (#22919)
  - [x] [Map between project.json and csproj](https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj) (**DELETE**) (#22919)
  - [x] [Map AssemblyInfo attributes to properties](https://docs.microsoft.com/en-us/dotnet/core/migration/assembly-info) (**MOVE** to the MSBuild info area) (#22918)
  - [x] [Changes in CLI overview](https://docs.microsoft.com/en-us/dotnet/core/tools/cli-msbuild-architecture) (**DELETE** conceptual material describing pre .NET Core 1 world) (#22919)
  - [x] [Migrate from DNX](https://docs.microsoft.com/en-us/dotnet/core/migration/from-dnx) (**DELETE** DNX material hasn't applied for years) (#22919)

- Port from .NET Framework
  - [x] [Overview](https://docs.microsoft.com/en-us/dotnet/core/porting/index) (**UPDATE/SPLIT** Article isn't really an overview. Lots of information, some steps to follow too, article has a mixed identity) (#23218)
  - [ ] [Analyze third-party dependencies](https://docs.microsoft.com/en-us/dotnet/core/porting/third-party-deps) (**UPDATE** Need better intro and flow)
  - [x] [Port libraries](https://docs.microsoft.com/en-us/dotnet/core/porting/libraries) (**UPDATE** Good information, should be pointed to by other articles such as port WPF) (#23218)
  - [x] [Organize projects for .NET](https://docs.microsoft.com/en-us/dotnet/core/porting/project-structure) (**INVESTIGATE** Describes code sharing. Probably more useful back when WinForms/WPF wasn't available. Not sure how relevant this is anymore) (#23218)
  - [x] [Unavailable technologies](https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable?toc=/dotnet/fundamentals/toc.json&bc=/dotnet/breadcrumb/toc.json) (**KEEP**) (#23218)
  - [x] [Tools](https://docs.microsoft.com/en-us/dotnet/core/porting/tools) (**DELETE** Too small. Move content to the overview article) (#23218)
  - [x] [Use the Windows Compatibility Pack](https://docs.microsoft.com/en-us/dotnet/core/porting/windows-compat-pack) (**UPDATE** Good information, should be pointed to by other articles such as port WPF) (#23218)
  - [x] [Port Windows Forms projects](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/migration/?view=netdesktop-5.0) (**KEEP**) (#23218)
  - [x] [Port WPF projects](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/migration/convert-project-from-net-framework) (**KEEP** Link is redirecting, fix) (#23218)
  - [x] [Port C++/CLI projects](https://docs.microsoft.com/en-us/dotnet/core/porting/cpp-cli) (**KEEP**) (#23218)

Possible future

- [x] Reference MSBuild Assembly Info attribute section in future content
- [x] File issue for MSBuild Assembly Info section to break out all of the individual settings
