### ISSUE TITLE
Tracking issue for missing documentation of .NET6 CAxxxx rules

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23900]
## TODO

- [ ] CA1419 added in https://github.com/dotnet/roslyn-analyzers/pull/5043.
- [ ] CA1727
- [ ] CA1842 and CA1843 added in https://github.com/dotnet/roslyn-analyzers/pull/4841
- [ ] CA1848
- [ ] CA2017
- [ ] CA2253
- [ ] CA2254 added in https://github.com/dotnet/roslyn-analyzers/pull/5244.
- [ ] CA2256
- [ ] CA2257
- [ ] CA2258

## Done

- [x] CA1418 added in https://github.com/dotnet/roslyn-analyzers/pull/4838.

- [x] CA1839 and CA1840 added in https://github.com/dotnet/roslyn-analyzers/pull/4909
- [x] CA1841 added in https://github.com/dotnet/roslyn-analyzers/pull/4687. Documentation PR https://github.com/dotnet/docs/pull/23887
- [x] CA1845 added in https://github.com/dotnet/roslyn-analyzers/pull/4764. Documentation PR https://github.com/dotnet/docs/pull/24270
- [x] CA1844 added in https://github.com/dotnet/roslyn-analyzers/pull/4726. Documentation PR https://github.com/dotnet/docs/pull/24278
- [x] CA1846 added in https://github.com/dotnet/roslyn-analyzers/pull/4806. Documentation PR https://github.com/dotnet/docs/pull/24325
- [x] CA1847 added in https://github.com/dotnet/roslyn-analyzers/pull/4908. Documentation PR #23377
- [x] CA1850 (Documentation PR https://github.com/dotnet/docs/pull/26634)
- [x] CA2018 added in https://github.com/dotnet/roslyn-analyzers/pull/5242.
- [x] CA2250 added in https://github.com/dotnet/roslyn-analyzers/pull/4864. Documentation PR https://github.com/dotnet/docs/pull/24324
- [x] CA2251 added in https://github.com/dotnet/roslyn-analyzers/pull/5116. Documentation PR https://github.com/dotnet/docs/pull/24463.
- [x] CA2255 added in https://github.com/dotnet/roslyn-analyzers/pull/5347.

See https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/RulesMissingDocumentation.md.

[CAxxxx docs guide](https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-contribute-code-analysis).

Tagging @buyaa-n @stephentoub @ryzngard @jkoritzinsky @NewellClark @MeikTranel who implemented these in case any of you wants to open a docs PR.

**Comment by mavasani** [comment]
Thank you so much for creating this doc isssue @Youssef1313! You are always one step ahead of us :-)

**Comment by mavasani** [comment]
Also tagging @jeffhandley as an FYI

**Comment by jeffhandley** [comment]
Adding @buyaa-n and @carlossanlop for their tracking.

**Comment by MeikTranel** [comment]
@Youssef1313 can you add https://github.com/dotnet/docs/pull/23377 to the CA1847 Rule point? I've reopened the issue a while ago.

**Comment by mikeKuester** [comment]
Visual Studio 2022 shows CA2254 warnings, but the link is broken? It is also missing in https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/
But if I look in the issue, it should be already merged?  "CA2254 added in Enabled logging analyzer on new repo roslyn-analyzers#5244."

**Comment by Youssef1313** [comment]
@mikeKuester The PR that's merged is that product PR. The docs PR isn't yet created. cc @maryamariyan

**Comment by mikeKuester** [comment]
Ok, it is a little bit strange, that a new analyser is deployed without an explanation. :(
At least from my user perspective.

**Comment by pcartwright81** [comment]
> @Youssef1313 Ok, it is a little bit strange, that a new analyser is deployed without an explanation. :( At least from my user perspective.

Is this analyser live in main or or preview?

**Comment by Bosch-Eli-Black** [comment]
It's been live in non-preview VS2022 for a while 🙂

**Comment by mikeKuester** [comment]
I didn't install the VS2022 preview, so it's live since the first VS2022 version. (actual 17.0.5)

**Comment by Youssef1313** [comment]
The issue is probably near to be fixed. See #27885

**Comment by Bosch-Eli-Black** [comment]
Yay! 🎉
