### ISSUE TITLE
Update existing dotnet/repos that rely on the .NET version sweeper

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#24032]
Update existing dotnet/repos that rely on the .NET version sweeper, targeting a specific version. Instead, have them target `@main` to benefit from implicit updates.

- [x] [Fix bug in sweeper](dotnet/versionsweeper#54)
- [x] [Fix dog-food.yml](dotnet/versionsweeper#55)
- [x] [dotnet/docs](#24033)
- [x] [dotnet/samples](dotnet/samples#4582)
- [x] [dotnet/dotnet-api-docs](dotnet/dotnet-api-docs#6716)
- [x] [dotnet/docs-desktop](dotnet/docs-desktop#1059)
