### ISSUE TITLE
Create Worker services overview article

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#24308]
The overview will explain conceptually some of the possible variants, and the overall concept of a worker service. It will quickly differentiate between `IHostedService` and the out-of-the-box `BackgroundService`. The overview will serve as an entry point into several tutorials:

- [x] https://github.com/dotnet/docs/issues/24304 - New `BackgroundService` tutorial
- [x] https://github.com/dotnet/docs/issues/24305 - New custom `IHostedService` impl tutorial
- [x] https://github.com/dotnet/docs/issues/24306 - Migration guide: Windows Service to `BackgroundService`
- [x] https://github.com/dotnet/docs/issues/24307 - Migration guide: Promote your on-premises worker service to the cloud

This new content will live under the **Runtime libraries** TOC node, here is its [Overview article](https://docs.microsoft.com/en-us/dotnet/standard/runtime-libraries-overview). Tentative TOC:

- Worker Services
  - Overview 
  - Tutorial: Use the BackgroundService
  - Tutorial: Custom `IHostedService` implemenation
  - Migrate: Windows Services to Worker Services
  - Migrate: On-prem Worker Services to the cloud

Peripheral content, and additional considerations:

- [Background tasks with hosted services][hosted]
- [.NET Core Workers as Windows Services][workers]
- [Tutorial: Create a Windows service app][components]
- [Develop Windows service apps][develop]

[hosted]: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services
[workers]: https://devblogs.microsoft.com/aspnet/net-core-workers-as-windows-services/
[components]: https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer
[develop]: https://docs.microsoft.com/en-us/dotnet/framework/windows-services

/cc @bradygaster

**Comment by bradygaster** [comment]
curious if @glennc has any thoughts, but I love the direction atm.
