### ISSUE TITLE
Update links (remove en-us+update MSDN links)

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#2580]
@mairaw I'll break these into batches on separate PRs:

- [x] Broken privacy link updates #2624 (merged)
- [x] Non-MSDN link updates #2625 (merged)
- [x] MSDN link updates
   * [ ] Convert the GUID-links #2632 (closed; merge conflicts; ran out of time to address them)
   * [x] Convert non-GUID links #2634 (in review)
- [x] Do the `azure.microsoft.com` ones, too! #2635 (merged)
- [ ] Convert absolute links to relative links. (on hold for others to merge)
- [ ] Manually fix those that can't be fixed by *mAd ScRiPtS*. 😵 (on hold for others to merge)

**Comment by GuardRex** [comment]
@mairaw I'll break these into three batches on three PRs:

- [ ] Broken privacy link updates in those feedback text sections (not the Third Party Notice)
- [ ] Non-MSDN link updates
- [ ] MSDN link updates
   * Convert the GUID-links to `library` links where possible
   * Swap-in OPS links when the MSDN link results in a redirect
   * Collect a list of 404 links (link, topic title, topic link, line number)

**Comment by mairaw** [comment]
Make sure you keep links inside the microservices book absolute.

**Comment by BillWagner** [comment]
Is this and #2037 duplicates?

**Comment by GuardRex** [comment]
@BillWagner These updates started with merely the goal of dropping `en-us` from links, then this was expanded to get rid of GUID-based MSDN links [either in favor of library-based MSDN links or OPS links (if the MSDN page redirects to an OPS topic)], update some privacy links, and fix some absolute links.

I think #2037 covers dealing more thoroughly with the entire MSDN and fwlink situation, and we've only done that lightly here.

The scripts I've used grab the canonical link from redirected responses to drop MSDN links where possible (especially the GUID-based ones in favor of the library-based ones), but as @mairaw already corrected on one of the PR's here, there's apparently many of them that won't get their correct OPS links. They simply didn't redirect to an OPS topic, so the script took the MSDN page at its library-based endpoint address for the link.

I think #2037 should be left open and worked on after this issue is resolved. The work on this issue pushes things in the right direction imo.

**Comment by GuardRex** [comment]
@mairaw Unassigning now ... I won't be able to address this issue further in the time remaining with the issues that I can finish by Monday night.

**Comment by mairaw** [comment]
Closing this since we have #2037 tracking this change more broadly.
