### ISSUE TITLE
[Project] .NET Core 2.0 and .NET Standard 2.0 releases

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2687]
This is a meta-issue for the [.NET Core 2.0](https://github.com/dotnet/docs/projects/17) project.

Comment below to suggest new content, or updates to existing content.

Scenarios:
- [ ] How to migrate from PCL to .NET Standard #2698
- [ ] How to migrate from .NET Framework to .NET Standard libraries #2699
- [ ] Create a path for Get Started with .NET Core #2700
- ~~Get Started C# topics showing new features in C# 7.1 #2701~~
- [ ] Moving projects to Docker #2702
- [ ] Add tutorial to show how to consume .NET Standard libraries with .NET Framework projects, for example #2712
- [x] Unit testing for .NET Core/.NET Standard #2713
- [ ] CI/CD flow (Azure DevOps) - community contributions for appveyor, .... #2714
- [ ] Show how to develop using different tools in different operating systems in a flow #2715
- [x] Deploying ASP.NET Core apps into Azure web apps - probably on the ASP.NET side but add links to this #2716
- [ ] Deploying .NET Core console apps into Azure web jobs (for batch jobs) #2717
- [ ] Secrets management (might already exist for web) #2718
- [x] How to uninstall the runtime/SDK on different platforms

Features:
- [x] OpenSSl no longer required for 2.0 #2144
- [x] Update Prerequisites for .NET Core on Mac #2492
- [x] Update Prerequisites for .NET Core on Windows #2696 
- [x] Add Prerequisites for .NET Core on Linux  #2719
- [x] Add VB support and samples as appropriate #2720
- [x] Update the .NET Core CLI commands #2721
- [x] Update topics that are using explicit dotnet restore #2722
- [x] Revisit version numbers and code snippets showing TFMs #2723
- [x] Add new TFMs #2091
- [x] Update versioning doc #2130
- [ ] Add guidance to use .NET Standard instead of PCL #2724
- [x] How to create custom templates #2405
- [x] dotnet store #2139
- [ ] metapackages changes -> .NET Core 1.x only now #2726
- ~~package resolution (1.x to 2.x dependencies) #2727~~
- [x] .NET Framework compat #2728
- [ ] assembly loading #2729
- [x] API Changes #2730
- [x] Binary serialization #2770 
- [x] Portable RIDs #2843
- [x] Roll forward policy/version binding #2880 
- [ ] Describe AssetTargetFallback #2816 
- [x] global.json changes #2902 
- [x] deployment changes #3059 

Announcements:
- [x] What's new in .NET Core 2.0 #2731
- ~~Migration guidance from 1.x to 2.0 - follow the same format as the framework #2732~~

Other:
- [ ] Validate Get started with Xamarin/.NET Core docs - https://developer.xamarin.com/guides/cross-platform/asp-net-core/ and https://developer.xamarin.com/guides/cross-platform/application_fundamentals/net-standard/

Edit: @billwagner Add links to new sub-issues that are part of this project.

**Comment by ViktorHofer** [comment]
@mairaw as discussed offline, please add https://github.com/dotnet/docs/issues/2770 to the list. (I don't have edit rights here)

**Comment by amdnaji** [comment]
@mairaw It will be really nice if we have a content about **ASP.NET Core** life cycle similar to this 
[https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/lifecycle-of-an-aspnet-mvc-5-application](url)

**Comment by Rick-Anderson** [comment]
>@mairaw It will be really nice if we have a content about ASP.NET Core life cycle similar to this
https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/lifecycle-of-an-aspnet-mvc-5-application

@amdnaji see https://github.com/aspnet/Docs/issues/3524

**Comment by mairaw** [comment]
Closing project issues.
