### ISSUE TITLE
[Epic]: C# 11 New features

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#30071]
The following tasks encompass new and updated features for C# 11:

- [x] [Develop a new page to keep track of (and point to) preview features #28243](https://github.com/dotnet/docs/issues/28243)
- [x] [Move preview features from C# 10 to C# 11 #28446](https://github.com/dotnet/docs/issues/28446)
- [x] [[17.1] Newlines in interpolations #28445](https://github.com/dotnet/docs/issues/28445)
- [x] [[17.1] Parameter null checking #28443](https://github.com/dotnet/docs/issues/28443)
- [x] [[17.2] Allow cached delegate for method groups #28942](https://github.com/dotnet/docs/issues/28942)
- [x] [[17.2] Raw string literals #28941](https://github.com/dotnet/docs/issues/28941)
- [x] [[17.1] List Patterns #28444](https://github.com/dotnet/docs/issues/28444)
- [x] [[17.3] Warning wave on lower case type names. #29265](https://github.com/dotnet/docs/issues/29265)
- [x] [[17.3] auto-default structs #29267](https://github.com/dotnet/docs/issues/29267)
- [x] [[17.3] Pattern match Span<char> on constant string #29270](https://github.com/dotnet/docs/issues/29270)
- [x] [[17.3] nameof parameter scope #29271](https://github.com/dotnet/docs/issues/29271)
- [x] [[17.3] Checked user defined operators #29268](https://github.com/dotnet/docs/issues/29268)
- [x] [[17.3] Unsigned right-shift operator #29266](https://github.com/dotnet/docs/issues/29266)
- [x] [[17.3] Relaxing shift operator requirements #29272](https://github.com/dotnet/docs/issues/29272)
- [x] [[17.3] numeric IntPtr #29625](https://github.com/dotnet/docs/issues/29625)
- [x] [[17.3] DIM for static members #29641](https://github.com/dotnet/docs/issues/29641)
- [x] [[17.3] Required members #29692](https://github.com/dotnet/docs/issues/29692)
- [x] [[17.3] UTF-8 string literals #29269](https://github.com/dotnet/docs/issues/29269)
- [x] #30226 
- [x] #30537

And last:

- [x] #30422
