### ISSUE TITLE
[EPIC] Orleans 💜 Cosmos DB

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#36975]
- [x] Update [Grain Persistence](https://learn.microsoft.com/dotnet/orleans/grains/grain-persistence/?pivots=orleans-7-0) page. Add NuGet package link, high level details of Cosmos grain. #36976
- [x] https://github.com/dotnet/docs/pull/37362
- [ ] Add new page for Cosmos Persistence Grain in Persistence TOC.
- [x] Update shopping cart sample to use Cosmos persistence grain.
- [x] Update [Contoso Monitoring sample](https://github.com/bradygaster/Contoso.Monitoring) to use Cosmos persistence grain.
  - Publish in Orleans .NET samples https://github.com/dotnet/samples/tree/main/orleans.

---
[Associated WorkItem - 156752](https://dev.azure.com/msft-skilling/Content/_workitems/edit/156752)

**Comment by markjbrown** [comment]
Note from meeting.

Orleans:

- Create new [Grain Persistence Page](https://learn.microsoft.com/en-us/dotnet/orleans/grains/grain-persistence/).

Cosmos:
- Update [Orleans Quickstart from Azure Storage](https://github.com/Azure-Samples/Orleans-Cluster-on-Azure-App-Service)
- Make this a tutorial geared towards a Cosmos user.

**Comment by seesharprun** [comment]
> Note from meeting.
> 
> Orleans:
> 
> * Create new [Grain Persistence Page](https://learn.microsoft.com/en-us/dotnet/orleans/grains/grain-persistence/).
> 
> Cosmos:
> 
> * Update [Orleans Quickstart from Azure Storage](https://github.com/Azure-Samples/Orleans-Cluster-on-Azure-App-Service)
> * Make this a tutorial geared towards a Cosmos user.
> 
> Everything on .NET 8 to align with IGNITE

Additional detail for Cosmos:

- Update quickstart to offer option to use Azure Cosmos DB or Azure Storage for persistence (https://github.com/Azure-Samples/build-your-first-orleans-app-aspnetcore).
- Create a tutorial focused on the [shopping cart sample](https://github.com/Azure-Samples/Orleans-Cluster-on-Azure-App-Service).

**Comment by seesharprun** [comment]
@alexwolfmsft for visibility

**Comment by seesharprun** [comment]
I have a draft PR open with an update to the shopping cart example in dotnet/samples:

- dotnet/samples#6213

**Comment by seesharprun** [comment]
I expect to have both draft PRs ready next week and will tag everyone on this thread for review.

**Comment by seesharprun** [comment]
@markjbrown:

I have updated the quickstart and grain persistence articles in this PR: 

- https://github.com/dotnet/docs/pull/37745

Here's the changes:

- The quickstart now uses `IsResourceCreationEnabled=true` to automatically create the database and container
- The grain persistence article now sets autoscale at the container level

**Comment by seesharprun** [comment]
After Ignite, I would like to change the sample application (https://github.com/Azure-Samples/build-your-first-orleans-app-aspnetcore) into an AZD template.

Here's what I'm thinking:

- The template uses in-memory storage by default. It also uses ACA as the host service with `mcr.microsoft.com/dotnet/samples:aspnetapp` as the default container image and ACR for any images built from the application.
- Clone and deploy the template with `azd init --template <template-name>` and `azd provision`. This will create the ACR and ACA resources. You could `azd up` here, but there's no point running the in-memory provider in Azure. You could also debug locally at this point.
- Edit the template's code to add the Azure Cosmos DB or Azure Storage grains.
- Change the `DEPLOY_AZURE_COSMOS_DB_NOSQL` or `DEPLOY_AZURE_BLOB_STORAGE` environment variables using `azd env set <variable-name> true`. They are set to false by default. Setting to true will ensure that these services are created and any managed identities are configured accordingly.
- Deploy the additional data service and updated code with `azd up`. This will create the data resources, build the container image, push to ACR, and then deploy the container image to ACA.
