### ISSUE TITLE
[EPIC] .NET 8 Data for Beginners video series

### ISSUE THREAD

**Issue by CamSoper** [dotnet/docs#37021]
Adapt EF Core for Beginners (.NET 6) content to new .NET Data for Beginners series (.NET 8)

- [x] Submit outlines
- [ ] Intro video - https://github.com/dotnet/docs/issues/41616
- [ ] SQL/ADO.NET - https://github.com/dotnet/docs/issues/41617
- [ ] Intro to Object Mappers: Dapper and Entity Framework Core - https://github.com/dotnet/docs/issues/41619
- [ ] Entity Framework Core Migrations
- [ ] Entity Framework Core Migrations
- [ ] Web apps with EF Core
- [ ] NoSQL
- [ ] Publishing

**Comment by CamSoper** [comment]
Back burnered
