### ISSUE TITLE
Create/Update conceptual docs for new System.Text.Json features in .NET 8

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/docs#37101]
Creating an issue to track creating new STJ conceptual docs in .NET 8, here's a list of key new features:

- [x] [Unmapped member handling](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/missing-members).
- [x] Update the `source-generation-modes` article to include sections on `TypeInfoResolverChain`, `JsonSerializerOptions.IsReflectionEnabledByDefault`, `JsonStringEnumConverter<TEnum>` and the `JsonSourceGenerationOptionsAttribute` extensions. Document the minimum language version (which has now been explicitly pegged to C# 9, cf. https://github.com/dotnet/runtime/pull/87950)(https://github.com/dotnet/runtime/issues/92877#issuecomment-1743365838).
- [x] Populating read-only properties in JSON. This feature carries a lot of nuance warranting documentation, @krwq has done a great job capturing the nitty-gritty details in the [original feature proposal](https://github.com/dotnet/runtime/issues/78556).
   - [x] This should additionally capture the problems of this feature with [parameterized constructors]
- [x] Update the `customize-properties` document to include mention for snake_case and kebab-case naming policies. This is also tracked by https://github.com/dotnet/docs/issues/36652.
- [x] Update the `migrate-from-newtonsoft` guide to mark the following as supported:
  - [x] MissingMemberHandling"
  - [x] "Snake-case property names"
  - [x] "Add to collections without setters" features
- [x] https://github.com/dotnet/docs/issues/36128
- [x] Document missing diagnostics (e.g. SYSLIB1034 and SYSLIB1039 and SYSLIB1220-SYSLIB1224) in https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/source-generator-overview (cf. https://github.com/dotnet/runtime/blob/main/docs/project/list-of-diagnostics.md)

I've posted an [article](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/) summarizing all new STJ features which can be used to feed into the content proposed above as well as other new conceptual docs where appropriate.

cc @gewarren @IEvangelist 

---
[Associated WorkItem - 164994](https://dev.azure.com/msft-skilling/Content/_workitems/edit/164994)
