### ISSUE TITLE
[Epic] Docs for new .NET Extensions

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#37411]
The following issue serves as an Epic, capturing task (issues) for individual work, such as but not limited to, conceptualizing and reasoning about various aspects of programming for .NET with numerous NuGet packages. Each package extends workload-agnostic cloud-native primitives, and fundamental building blocks for creating resilient, diagnostic-empowered, and robust features like health-checks and dependency injection (DI) auto-activation.

Each conceptual article with be interleaved into an appropriate section (or sub-section) of the [existing .NET libraries content](https://learn.microsoft.com/dotnet/standard/runtime-libraries-overview). 

> **Important**
> The following two subsets, track currently published NuGet packages, publicly available in a prerelease state. If they're not listed here, then they're not going to have a conceptual article written for them:

**.NET Extensions:**

- [x] [`Microsoft.Extensions.Http.AutoClient`](https://www.nuget.org/packages/Microsoft.Extensions.Http.AutoClient)
  - PR: #36970 — 👀: [<kbd>Ctrl</kbd> + 👆 for live](https://learn.microsoft.com/dotnet/fundamentals/networking/http/http-autoclient)
- [x] [`Microsoft.Extensions.Resilience`](https://www.nuget.org/packages/Microsoft.Extensions.Resilience)
  - PR: #37270 — 👀: [<kbd>Ctrl</kbd> + 👆 for live](https://learn.microsoft.com/dotnet/core/resilience)
- [x] [`Microsoft.Extensions.Http.Resilience`](https://www.nuget.org/packages/Microsoft.Extensions.Http.Resilience)
  - PR: #37270 — 👀: [<kbd>Ctrl</kbd> + 👆 for live](https://learn.microsoft.com/dotnet/core/resilience/http-resilience)
- [x] [`Microsoft.Extensions.Diagnostics.Probes`](https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics.Probes)
  - PR: #37455 — 👀: [<kbd>Ctrl</kbd> + 👆 to preview](https://review.learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-libraries?branch=main#kubernetes-probes)
- [x] [`Microsoft.Extensions.Diagnostics.ResourceMonitoring`](https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics.ResourceMonitoring)
  - PR: #37455 — 👀: [<kbd>Ctrl</kbd> + 👆 to preview](https://review.learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-libraries?branch=main#resource-monitoring)
- [x] [`Microsoft.Extensions.Diagnostics.ExceptionSummarization`](https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics.ExceptionSummarization) 
  - PR: #37455 — 👀: [<kbd>Ctrl</kbd> + 👆 to preview](https://review.learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-libraries?branch=main#exception-summarization)
- [x] [`Microsoft.Extensions.Diagnostics.HealthChecks.Common`](https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics.HealthChecks.Common)
  - PR: #37455 — 👀: [<kbd>Ctrl</kbd> + 👆 to preview](https://review.learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-libraries?branch=main#application-lifetime-health-checks)
- [x] [`Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization`](https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization)
  - PR: #37455 — 👀: [<kbd>Ctrl</kbd> + 👆 to preview](https://review.learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-libraries?branch=main#resource-utilization-health-checks)
- [x] [`Microsoft.Extensions.DependencyInjection.AutoActivation`](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.AutoActivation)
  - PR: https://github.com/dotnet/docs/pull/49372
- [x] [`Microsoft.Extensions.AsyncState`](https://www.nuget.org/packages/Microsoft.Extensions.AsyncState)
  - PR: https://github.com/dotnet/docs/pull/49372
- [x] [`Microsoft.Extensions.AmbientMetadata.Application`](https://www.nuget.org/packages/Microsoft.Extensions.AmbientMetadata.Application)
  - PR: https://github.com/dotnet/docs/pull/51192
- [x] [`Microsoft.Extensions.TimeProvider.Testing`](https://www.nuget.org/packages/Microsoft.Extensions.TimeProvider.Testing)
  - PR: https://github.com/dotnet/docs/pull/49372
- [x] [`Microsoft.Extensions.AuditReports`](https://www.nuget.org/packages/Microsoft.Extensions.AuditReports)
  - PR: https://github.com/dotnet/docs/pull/49372

**ASP.NET Core**:

I'm going to tag @Rick-Anderson here, who from the ASP.NET Docs team can write a new conceptual article for the following NuGet package?

- [ ] [`Microsoft.AspNetCore.HeaderParsing`](https://www.nuget.org/packages/Microsoft.AspNetCore.HeaderParsing)

---
[Associated WorkItem - 500373](https://dev.azure.com/msft-skilling/Content/_workitems/edit/500373)
