### ISSUE TITLE
[Epic] Freshness updates for C# articles

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#39819]
### Describe the issue or suggestion

There are several high-traffic articles in the C# guide that haven't been reviewed or updated in some time. A few have already been identified for a complete rewrite. This epic captures the others that should be reviewed and may need light edits.

- [x] [Access modifiers](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)  **Bill**
  - See #25518
  - See #27155
  - See #27196 
  - See #27197
- [x] [Constraints on type parameters](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/generics/constraints-on-type-parameters.md) **Bill**
  - See #11835
  - See #28647
  - See #28914 
  - See #30529 
- [x] [Partial classes and methods](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/partial-classes-and-methods.md) **Bill**
  - See #26542 
  - See #30017
  - See #31318 
- [x] [How to parse strings using `String.Split`](https://github.com/dotnet/docs/blob/main/docs/csharp/how-to/parse-strings-using-split.md) - **Cam**
  - See #20123 for an open issue
  - See #29825 for an open issue
- [x] [Pattern matching overview](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/functional/pattern-matching.md) **Bill**
  - See #29821 for an open issue
- [x] [Main and command line arguments](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/program-structure/main-command-line.md) **Cam**
  - See #27207 for an open issue
- [x] [Named and optional arguments](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/named-and-optional-arguments.md) **Cam**
  - See #32702 
- [x] [Generics](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/generics.md) **Bill**
  - See #29778 
- [x] [Using Properties](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/using-properties.md) **Bill**
  - See #32071
- [x] [How to compare strings](https://github.com/dotnet/docs/blob/main/docs/csharp/how-to/compare-strings.md) **Bill**
  - See #23932
- [x] [How to convert a string to a number](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/types/how-to-convert-a-string-to-a-number.md)
- [x] [Extension methods](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/extension-methods.md)
- [x] [Strings and string literals](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/strings/index.md)
- [x] [How to initialize a dictionary with a collection initializer](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/how-to-initialize-a-dictionary-with-a-collection-initializer.md)
- [x] [Unit testing in .NET Core using xUnit](https://github.com/dotnet/docs/issues/39866) Let's change the title. **-Cam**
- [x] [How to concatenate multiple strings](https://github.com/dotnet/docs/blob/main/docs/csharp/how-to/concatenate-multiple-strings.md)
- [x] [How to write a text file](https://github.com/dotnet/docs/blob/main/docs/standard/io/how-to-write-text-to-a-file.md)
- [x] [Casting and type conversions](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/types/casting-and-type-conversions.md)
- [x] [Static classes and static members](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md)
- [x] [Properties](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/properties.md)
- [x] [C# Programming guide](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/index.md): This one is a link / index page that should be retired. **Bill**

These are introductory tutorials that are likely all up to date, and should only need meta data updates (except as noted):

- [x] [Introductory tutorials](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/index.md)
  - See #31596 for an open issue
- [x] [Hello World!](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/hello-world.yml)

What's new article for older versions:

- [x] [What's new in C# 11](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-11.md)

This one is not in the C# area, but covers the C# console template.

- [x] [Top level templates](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)

---
[Associated WorkItem - 226913](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226913)
