### ISSUE TITLE
[Project] .NET Core 2.1 release

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/docs#4390]
This is a meta-issue for the [.NET Core 2.1](https://github.com/dotnet/docs/projects/34) project. 

Comment below to suggest new content, or updates to existing content.

Scenarios:
- Deployment
   - [ ] .NET Core Global Tools
- Porting
   - [ ] Windows Compatibility Pack Overview
      - [ ] Guidance
          - [ ] Cross Platform 
      - [ ] Getting Started and Tutorials 
- Platform
   - Building on Windows, cross-targeting to other platforms
   - Dev on Windows / deploy to Linux and reverse   
- High Performance
  - [ ] Span \<T\> & Friends Overview- Providing contiguous windows of data without needing to make a copy 
    - [ ] Working with stack and heap (lifetime and storage)

.NET Core 2.0, updated for .NET Core 2.1 Content Backlog:

Features:
- [ ] .NET Core 2.1 Reference API - document APIs
   - [x] Span<T>
   - [ ] ReadOnlySpan<T>
   - [ ] Memory<T>
   - [ ] Pipelines
- [ ] .NET Core Global Tools 
   - [ ] Part 1 #4509
   - [ ] Part 2 #6016
   - [ ] Part 3 #6017
- [ ] Patch Management
- [x] Revisit and revise .NET Core SDK Commands #4627
- [x] SDK Minor Version Roll-forward #4540 
   - [x] Update Version Topic 
- [ ] Runtime Minor Version Roll-forward  
- [ ] Windows Compatibility Pack #4628
    - [ ] What's in it?
- [x ] Span\<T\> #4400 Overview
   - [ ] Memory\<T\> #4823
   - [ ] Span UTF-8 parsing overview
   - [ ] Buffer best practices 
   - [ ] Ref struct overview - needs to be expanded (.NET Guide)
     (Refer to 7.2 content)
- [ ] Update Deployment Topic
     - [ ] Runtime Updates - review RIDs

- [ ] Tiered compilation overview
- [ ] HttpClient Listener rewritten for performance #4541 
       - [ ]  HttpClient Listener rewritten for performance 
       - [ ]  Significant changes in 2.1 -> How to get the old version 
- [ ] System.IO changes #4483 
- [ ] ARM32 and Alpine support #4663 
       - [ ] Alpine-3.6 is now linux-MUSL

Moving from .NET Core 2.0
- [ ] Add guidance to use .NET Standard instead of PCL #2724
- [ ] CI/CD flow (VSTS) - community contributions for appveyor, .... #2714
- [ ] Deploying .NET Core console apps into Azure web jobs (for batch jobs) #2717
- [ ] Moving projects to Docker #2702
- [ ] https://aka.ms/dotnet-install-templates has bad redirect + No "Install templates docs" #3178
- [ ] Create a path for Get Started with .NET Core #2700
- [ ] Document how to use cryptography in a cross-plat way #761
- [ ] Add topic on runtimeconfig.json #2645
- [ ] Document including runtime specific packages via runtime.json #1345
- [ ] How to migrate from PCL to .NET Standard #2698 
- [ ] Document default compiler defines #1483
- [ ] Secrets management #2718
- [ ] Add tutorial to show how to consume .NET Standard libraries with .NET Framework projects, for example #2712
- [ ] .NET Framework compatibility #2728
- [ ] Migration Guidance for .NET Core 1.x to .NET Core 2.0 #2732
- [ ] Multitargeting topic should include guidance on testing and debugging against a specific target #1772
- [ ] Version binding for .NET Core 2.0 #2880
- [ ] Revisit version numbers and code snippets showing TFMs #2723

Announcements:
- What's new in .NET Core 2.1 #4933
    - [ ] Build-time Performance 

Other:
- [x] Added note about SDK 2.1 #4385 - Clarifying versioning. 
- [ ] SDK and Runtime Versioning #4352 
- [ ] New and Improved Docker Images
- [ ] Review and revise Prerequisite articles
- [x] Review topics that have ms.custom: "updateeachrelease" (that are not framework specific) such as [https://docs.microsoft.com/en-us/dotnet/standard/frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks ) 
- [x] Remove SignalR from list of technologies not available on ,NET Core (https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server)
- [ ] Content Move - Network programming and ADO.NET to .NET Guide instead of Fx.
- [ ] .NET Core 2.1 SDK - what language versions are included in each release?
- [ ] Need to determine which .NET Core SDK has which C# version enabled #4154
- [x] Document System.Hashcode in .NET Core 2.1 API #4936
edit by @mairaw: added new work items

**Comment by dasMulli** [comment]
Is there a plan to start an area or branch with preview docs for 2.1 already? Some of the work items may be helpful during the preview timeframe (e.g. global tools, versioning, roll-forward) to help (and even make) ppl try out preview features.

**Comment by mairaw** [comment]
Hi @dasMulli, some we might start working on that soon like global tools. I think we won’t create a different folder/area for 2.1. We’ll add things as they make sense in the TOC. We’ll go through a prioritization exercise for our 2.1 work vs. remaining 2.0 work as well to see what to work on next.

**Comment by mairaw** [comment]
You can create a new issue for that @ChrisMaddock. There are quite a few undocumented APIs for the .NET reference and an ongoing project for filling those gaps: https://github.com/dotnet/docs/projects/15.

We also created an internal report to discover all those. But the ones captured here were the ones considered high-priority for the release. Makes sense?

**Comment by ChrisMaddock** [comment]
Thanks @mairaw - I've moved it here: https://github.com/dotnet/docs/issues/4936

**Comment by JRAlexander** [comment]
Thanks, @ChrisMaddock, I've added it in this issue above, and also in the [.NET Core 2.1 project] (https://github.com/dotnet/docs/projects/34).

**Comment by mairaw** [comment]
We no longer track projects with issues. Closing.
