### ISSUE TITLE
[Project] .NET Framework 4.7.2

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4792]
This is a meta-issue for the .NET Framework 4.7.2 project.

Comment below to suggest new content, or updates to existing content.

Work items:

- [x] What's new in .NET Framework 4.7.2 #4793
- [x] What's new in accessibility in the .NET Framework 4.7.2 #4818 
- [x] What's obsolete #4794
- [x] Migration Guide updates #4795
- [x] Installation Guide updates #4796
- [x] Deployment Guide updates
- [x] Revisit other topics tagged with updateeachrelease ms.custom value
- [x] Document new APIs #4876

/cc @rpetrusha
