### ISSUE TITLE
Markdig migration preparation - master issue - round 1

### ISSUE THREAD

**Issue by scottaddie** [dotnet/docs#6581]
The docs below, in the *master* branch, were flagged during the test run of the Markdig migration. Refer to the spreadsheet's *DifferenceAfterMigration* tab for more details, and apply the following column filter:

- *Migrated* = True

The *SourceMarkdown* column contains the offending Markdown. Changes can be validated in the *markdig-migration* branch. Refer to [Markdig Migration Information](https://review.docs.microsoft.com/en-us/new-hope/engineering/tools/markdig/markdig-migration-information?branch=master&tabs=dfm) for syntax guidance.

## _vblang (@rpetrusha)
- [x] _vblang/spec/general-concepts.md

## docs/core (@mairaw)
- [x] docs/core/whats-new/dotnet-core-2-1.md

## docs/csharp (@BillWagner)
- [x] docs/csharp/async.md
- [x] docs/csharp/programming-guide/concepts/linq/how-to-create-a-document-with-namespaces-linq-to-xml.md
- [x] docs/csharp/programming-guide/statements-expressions-operators/statements.md

## docs/framework (@rpetrusha)
- [x] docs/framework/data/adonet/common-schema-collections.md
- [x] docs/framework/data/adonet/configuring-parameters-and-parameter-data-types.md
- [x] docs/framework/data/adonet/ef/aggregate-functions-sqlclient-for-entity-framework.md
- [x] docs/framework/data/adonet/ef/language-reference/aggregate-canonical-functions.md
- [x] docs/framework/data/adonet/ef/language-reference/math-canonical-functions.md
- [x] docs/framework/data/adonet/ef/mathematical-functions.md
- [x] docs/framework/data/wcf/query-projections-wcf-data-services.md
- [x] docs/framework/net-native/directives-element-net-native.md
- [x] docs/framework/network-programming/certificate-selection-and-validation.md
- [x] docs/framework/network-programming/changes-to-the-system-uri-namespace-in-version-2-0.md
- [x] docs/framework/network-programming/how-to-override-a-global-proxy-selection.md
- [x] docs/framework/network-programming/listening-with-sockets.md
- [x] docs/framework/network-programming/managing-connections.md
- [x] docs/framework/security/wstrustchannelfactory-and-wstrustchannel.md
- [x] docs/framework/tools/caspol-exe-code-access-security-policy-tool.md
- [x] docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
- [x] docs/framework/wcf/feature-details/deploying-an-internet-information-services-hosted-wcf-service.md
- [x] docs/framework/wcf/feature-details/endpoint-addresses.md
- [x] docs/framework/wcf/feature-details/how-to-add-an-aspnet-ajax-endpoint-without-using-configuration.md
- [x] docs/framework/wcf/feature-details/how-to-install-and-configure-wcf-activation-components.md
- [x] docs/framework/wcf/feature-details/how-to-use-configuration-to-add-an-aspnet-ajax-endpoint.md
- [x] docs/framework/wcf/feature-details/how-to-use-filters.md
- [x] docs/framework/wcf/feature-details/http-post-and-http-get-requests-for-aspnet-ajax-endpoints.md
- [x] docs/framework/wcf/feature-details/working-with-certificates.md
- [x] docs/framework/wcf/samples/aspnet-compatibility.md
- [x] docs/framework/wcf/samples/hello-world-with-the-routing-service.md
- [x] docs/framework/wcf/samples/hierarchical-configuration-model.md
- [x] docs/framework/wcf/samples/poison-message-handling-in-msmq-4-0.md
- [x] docs/framework/wcf/samples/systemwebrouting-integration-sample.md
- [x] docs/framework/wcf/samples/usage-of-standard-endpoints.md
- [x] docs/framework/wcf/specifying-an-endpoint-address.md
- [x] docs/framework/wcf/troubleshooting-the-getting-started-tutorial.md
- [x] docs/framework/whats-new/index.md
- [x] docs/framework/whats-new/obsolete-members.md
- [x] docs/framework/windows-workflow-foundation/consuming-odata-feeds-from-a-workflow.md
- [x] docs/framework/windows-workflow-foundation/how-to-enable-sql-persistence-for-workflows-and-workflow-services.md
- [x] docs/framework/wpf/advanced/use-automatic-layout-overview.md
- [x] docs/framework/wpf/graphics-multimedia/graphics-rendering-registry-settings.md
- [x] docs/framework/wpf/graphics-multimedia/storyboards-overview.md
- [x] docs/framework/xaml-services/x-static-markup-extension.md

## docs/fsharp (@BillWagner)
- [x] docs/fsharp/tutorials/type-providers/creating-a-type-provider.md

## docs/standard (@mairaw)
- [x] docs/standard/base-types/custom-date-and-time-format-strings.md
- [x] docs/standard/base-types/custom-timespan-format-strings.md
- [x] docs/standard/base-types/enumeration-format-strings.md
- [x] docs/standard/data/xml/implementation-of-discretionary-behaviors-in-the-xsltransform-class.md
- [x] docs/standard/io/how-to-find-existing-files-and-directories-in-isolated-storage.md
- [x] docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md
- [x] docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/client-side-validation.md
- [x] docs/standard/serialization/introducing-xml-serialization.md

## docs/visual-basic (@rpetrusha)
- [x] docs/visual-basic/language-reference/queries/aggregate-clause.md
- [x] docs/visual-basic/programming-guide/language-features/control-flow/walkthrough-implementing-ienumerable-of-t.md
- [x] docs/visual-basic/programming-guide/language-features/linq/introduction-to-linq.md
- [x] docs/visual-basic/programming-guide/language-features/statements.md

**Comment by mairaw** [comment]
I'll start with core and standard folders.

**Comment by BillWagner** [comment]
I'll start with the C# folders.

**Comment by Thraka** [comment]
I'll help with @rpetrusha in the docs/framework section. I'll start at the bottom.

**Comment by JRAlexander** [comment]
I'll help with standard - and also start from bottom.

**Comment by mairaw** [comment]
standard is done already @JRAlexander. See PR #6766. Please take another one.

**Comment by JRAlexander** [comment]
Ok, I'll mark them above as such.

**Comment by JRAlexander** [comment]
I'll start on VB.

**Comment by BillWagner** [comment]
I'll take the F# article.

**Comment by mairaw** [comment]
Round 1 is over @scottaddie, so I'm closing this one. We need to ask for an updated report and perhaps a report for the dotnet-api-docs repo.
