### ISSUE TITLE
Markdig migration preparation - master issue - round 2

### ISSUE THREAD

**Issue by scottaddie** [dotnet/docs#7201]
The docs below, in the *master* branch, were flagged during the test run of the Markdig migration. Refer to the spreadsheet's *DifferenceAfterMigration* tab for more details, and apply the following column filter:

- *Migrated* = True

The *SourceMarkdown* column contains the offending Markdown. Changes can be validated in the *markdig-migration* branch. Refer to [Markdig Migration Information](https://review.docs.microsoft.com/en-us/new-hope/engineering/tools/markdig/markdig-migration-information?branch=master&tabs=dfm) for syntax guidance.

## _vblang
- [ ] spec/general-concepts.md

## docs/core
- [x] whats-new/dotnet-core-2-1.md

## docs/framework
- [x] whats-new/index.md
- [x] network-programming/certificate-selection-and-validation.md
- [x] network-programming/changes-to-the-system-uri-namespace-in-version-2-0.md
- [x] wpf/advanced/use-automatic-layout-overview.md

## docs/fsharp
- [x] tutorials/type-providers/creating-a-type-provider.md

## docs/standard
- [x] io/how-to-find-existing-files-and-directories-in-isolated-storage.md
- [x] base-types/custom-date-and-time-format-strings.md
- [x] base-types/custom-timespan-format-strings.md
- [x] base-types/enumeration-format-strings.md

## docs/visual-basic
- [x] language-reference/queries/aggregate-clause.md
- [x] programming-guide/language-features/linq/introduction-to-linq.md

**Comment by mairaw** [comment]
Not too bad. I did the core folder already and will look into the VB folder next.

**Comment by Thraka** [comment]
Grabbing docs/framework
