### ISSUE TITLE
Markdig migration preparation - master issue - final round

### ISSUE THREAD

**Issue by scottaddie** [dotnet/docs#8480]
The docs below, in the *master* branch, were flagged during the test run of the Markdig migration. Refer to the spreadsheet's *DifferenceAfterMigration* tab for more details. The *SourceMarkdown* column contains the offending Markdown.

If changes are necessary, they can be validated in the *markdig-migration* branch. Refer to [Markdig Migration Information](https://review.docs.microsoft.com/en-us/new-hope/engineering/tools/markdig/markdig-migration-information?branch=master&tabs=dfm) for syntax guidance. **Compare the review page for the *markdig-migration* branch against the review page for the *live* branch.**  

## _csharplang
- [x] spec/expressions.md

## _vblang
- [x] spec/general-concepts.md

## docs/framework
- [x] configure-apps/file-schema/runtime/throwunobservedtaskexceptions-element.md
- [x] configure-apps/file-schema/wcf-directive/index.md
- [x] configure-apps/file-schema/wcf-directive/servicehost.md
- [x] develop-web-apps-with-aspnet.md
- [x] interop/marshaling-data-with-platform-invoke.md
- [x] migration-guide/retargeting/4.0-4.7.1.md
- [x] migration-guide/retargeting/4.0-4.7.2.md
- [x] migration-guide/retargeting/4.0-4.7.md
- [x] migration-guide/retargeting/4.5.1-4.7.1.md
- [x] migration-guide/retargeting/4.5.1-4.7.2.md
- [x] migration-guide/retargeting/4.5.1-4.7.md
- [x] migration-guide/retargeting/4.5.2-4.7.1.md
- [x] migration-guide/retargeting/4.5.2-4.7.2.md
- [x] migration-guide/retargeting/4.5.2-4.7.md
- [x] migration-guide/retargeting/4.5-4.7.1.md
- [x] migration-guide/retargeting/4.5-4.7.2.md
- [x] migration-guide/retargeting/4.5-4.7.md
- [x] migration-guide/retargeting/4.6.1-4.7.1.md
- [x] migration-guide/retargeting/4.6.1-4.7.2.md
- [x] migration-guide/retargeting/4.6.1-4.7.md
- [x] migration-guide/retargeting/4.6.2-4.7.1.md
- [x] migration-guide/retargeting/4.6.2-4.7.2.md
- [x] migration-guide/retargeting/4.6.2-4.7.md
- [x] migration-guide/retargeting/4.6-4.7.1.md
- [x] migration-guide/retargeting/4.6-4.7.2.md
- [x] migration-guide/retargeting/4.6-4.7.md
- [x] migration-guide/retargeting/4.7-4.7.1.md
- [x] migration-guide/retargeting/4.7-4.7.2.md
- [x] net-native/migrating-your-windows-store-app-to-net-native.md
- [x] network-programming/peer-name-publication-and-resolution.md
- [x] network-programming/peer-name-resolution-protocol.md
- [x] network-programming/peer-to-peer-collaboration.md
- [x] performance/writing-large-responsive-apps.md
- [x] reflection-and-codedom/how-to-create-a-class-using-codedom.md
- [x] ui-automation/access-embedded-objects-using-ui-automation.md
- [x] ui-automation/find-and-highlight-text-using-ui-automation.md
- [x] ui-automation/obtain-mixed-text-attribute-details-using-ui-automation.md
- [x] ui-automation/traverse-text-using-ui-automation.md
- [x] ui-automation/ui-automation-support-for-the-list-control-type.md
- [x] unmanaged-api/debugging/icordebugblockingobjectenum-next-method.md
- [x] unmanaged-api/metadata/imetadataemit-definefield-method.md
- [x] unmanaged-api/metadata/imetadataemit-defineparam-method.md
- [x] unmanaged-api/metadata/imetadataemit-setfieldprops-method.md
- [x] wcf/configuring-services-using-configuration-files.md
- [x] wcf/extending/extensible-objects.md
- [x] wcf/feature-details/how-to-retrieve-metadata-and-implement-a-compliant-service.md
- [x] wcf/feature-details/messaging-protocols.md
- [x] wcf/feature-details/using-message-contracts.md
- [x] wcf/specifying-service-run-time-behavior.md
- [x] windows-workflow-foundation/how-to-create-a-custom-tracking-participant.md
- [x] windows-workflow-foundation/how-to-host-multiple-versions-of-a-workflow-side-by-side.md
- [x] windows-workflow-foundation/performance.md
- [x] windows-workflow-foundation/samples/sendmail-custom-activity.md
- [x] winforms/advanced/how-to-create-graphics-objects-for-drawing.md
- [x] winforms/controls/how-to-add-or-remove-images-with-the-windows-forms-imagelist-component.md
- [x] wpf/advanced/attached-properties-overview.md
- [x] wpf/advanced/bidirectional-features-in-wpf-overview.md
- [x] wpf/advanced/use-automatic-layout-overview.md
- [x] wpf/advanced/wpf-globalization-and-localization-overview.md
- [x] wpf/controls/calendar-styles-and-templates.md
- [x] wpf/controls/index.md
- [x] wpf/data/how-to-sort-data-in-a-view.md (markdig issue - deleting comment from xaml snippet referenced)

## docs/fsharp
- [x] language-reference/verbose-syntax.md

## docs/standard
- [x] base-types/custom-date-and-time-format-strings.md
- [x] base-types/custom-timespan-format-strings.md
- [x] base-types/enumeration-format-strings.md
- [x] io/how-to-find-existing-files-and-directories-in-isolated-storage.md

## docs/visual-basic
- [x] misc/a-delimiter-cannot-be-nothing-or-an-empty-string.md
- [x] misc/bc30981.md
- [x] misc/bc31199.md
- [x] misc/bc31536.md
- [x] misc/bc31537.md
- [x] misc/bc31538.md
- [x] misc/bc36613.md
- [x] misc/bc36614.md
- [x] misc/bc42207.md
- [x] misc/bc42322.md
- [x] misc/bc42328.md

**Comment by BillWagner** [comment]
I'll handle the **_csharplang** changes.  (then more)

**Comment by mairaw** [comment]
I'll start checking the visual-basic ones.

**Comment by BillWagner** [comment]
Verified that no changes are needed in **_csharplang/expressions.md**

**Comment by mairaw** [comment]
Fixed one problematic issue in the **visual-basic** folder. The others are "by design" since the content is missing so the numbered list has no content. I'll check standard next.

**Comment by rpetrusha** [comment]
I'm doing the additional .NET Framework issues as well.

**Comment by BillWagner** [comment]
I'll work on standard and F# tonight.

**Comment by mairaw** [comment]
I'm back from my appointment. I can finish those @BillWagner.

**Comment by mairaw** [comment]
I also sent an email to the eng team about the warnings showing up on the build report. They're really strange.

**Comment by mairaw** [comment]
starting on framework from bottom up. For wpf/data/how-to-sort-data-in-a-view.md, I've noticed that part of the XAML code disappears on the markdig version.

**Comment by BillWagner** [comment]
starting on WinForms now...

**Comment by BillWagner** [comment]
starting on workflow...

**Comment by BillWagner** [comment]
Starting WCF now.

**Comment by mairaw** [comment]
Closing this one since Markdig migration is done. I think some of the issues I called out earlier are still happening though so we need to follow up with the engineering team on that if it is. /cc @scottaddie

**Comment by mairaw** [comment]
Never mind. Issue was fixed!
