### ISSUE TITLE
Create the Getting Started topic for the C# Guide

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#942]
The getting-started section (http://github.com/docnet/core-docs/blob/master/docs/csharp/getting-started/index.md) index should contain:
- general information about the different environments and platforms where C# can be used.
- general information about acquiring C# and the .NET tools.
- links to the other getting started content.

When writing this, call out C# interactive (and its getting started topic) as a way to explore the language with minimal installation overhead.

These are the identified sub-issues for this issue:
- [ ] #943  Getting Started with Visual Studio
- [ ] #944 Getting Started with Visual Studio Code
- [ ] #945 Getting started with the cross platform command line tools
- [ ] #946 Getting started with C# interactive.

**Comment by BillWagner** [comment]
@tompratt-AQ Putting all of this under your umbrella. Let me know if you need more information than the notes on these issues.

**Comment by BillWagner** [comment]
The topics under the current csharp/getting-started are really centered on .NET Core as a platform. In fact, all the tutorials focus on building an assembly (library, or executable) for .NET Core. They also cover unit testing (if only briefly).

So, what should happen is this:

1. The existing topics, which focus on .NET Core as a platform should find a new location under [getting-started with .NET Core](https://github.com/dotnet/docs/blob/master/docs/core/getting-started.md). This might include a bit of merging, but it looks like these are different topics.
2. New topics that focus more on the language should be under this node in the C# Guide. These “Getting started with C#” topics would have a different audience, and should have a different emphasis. The Core getting started topics are more about the platform, and will include some readers that have .NET experience but don’t have Core and cross platform experience. The C# getting started should be more of a tour of the language, with less of an emphasis on the tools and the platform.  I want to aim for something like a shortened version of the “Tour of C#” here: https://docs.microsoft.com/en-us/dotnet/articles/csharp/tour-of-csharp/. The goal should be a 10 – 15 minute read that provides some of the basic constructs in the language. The target audience is developers that have never used C#, but may have experience with other languages.

As you write, we may be able to manage just two: one for using Visual Studio, and one for VS Code on the Mac. The VS Code on the Mac and VS Code on Windows may be similar enough not to require different topics. If we do that, I want to make sure that any screen shots are clearly Mac, so those customers can easily see that C# runs cross platform.

**Comment by BillWagner** [comment]
Closing this as the get started experience will change in the next major rev of the C# Guide.
