### ISSUE TITLE
C# Guide: C# Interactive Home Pages

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#968]
This issue tracks the topic for https://github.com/dotnet/docs/blob/master/docs/csharp/interactive/index.md

The home page for C# interactive should cover common scenarios for using the interactive REPL. These include:
- learning C#
- exploring a framework API
- exploring a REST API using the .NET Framework APIS
- prototyping and generating a working class as output

This list isn't meant to be exhaustive, as this topic gets flushed out, more ideas may emerge.

Subtasks are:
- [ ] #969 Using C# Interactive with Visual Studio
- [ ] #970 Using C# Interactive with Powershell
- [ ] #971 Using C# Interactive with MacOS or Linux terminal

**Comment by GuardRex** [comment]
Reconstitute the TOC when any one of these is created. Original file contents shown below when stubs were present:
```
# [🔧 C# Interactive](index.md)
## [🔧 Using C# Interactive in Visual Studio](with-visualstudio.md)
## [🔧 Using C# Interactive from Powershell](with-powershell.md)
## [🔧 Using C# Interactive from macOS or Linux Terminal](with-bash.md)
```

**Comment by BillWagner** [comment]
This doesn't match the updated plans for the C# Guide. Closing.
